site_name: coredump build logs
theme: yeti
google_analytics: [ UA-41494372-2, 'auto' ]
site_url: http://coredump.io/buildlogs
repo_url: https://github.com/coredump/buildlogs
markdown_extensions:
  - smarty
  - admonition
  - footnotes
  - toc
extra_css:
  - css/admonitions.css
  - css/shariff.complete.css
extra_javascript:
  - js/shariff.complete.js
copyright: "&copy; 2016 Jose Junior. Some rights reserved."
site_description: Some DIY adventures
site_author: Jose Junior (coredump)
pages:
  - "home": index.md
  - logs:
    - "custom 1 fightstick": custom1.md
    - "clueboard 2 mechanical keyboard": clueboard2.md
    - "custom 2 fightstick": custom2.md
  - contact: contact.md
