site_name: coredump build logs
theme: yeti
google_analytics: [ UA-41494372-2, 'auto' ]
site_url: http://coredump.io/buildlogs
markdown_extensions:
  - smarty
  - admonition
extra_css:
  - css/admonitions.css
copyright: "&copy; 2016 Jose Junior. Some rights reserved."
site_description: Some DIY adventures
site_author: Jose Junior (coredump)
pages:
  - "home": index.md
  - "custom 1 fightstick": custom1.md
